//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronikaiAlkatreszKeszletNyilvantarto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alkatresz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alkatresz()
        {
            this.Parameter = new HashSet<Parameter>();
            this.Prj_Alkatresz = new HashSet<Prj_Alkatresz>();
        }
    
        public int ALKATRESZ_ID { get; set; }
        public int KATEGORIA_ID { get; set; }
        public int PARAMETER_ID { get; set; }
    
        public virtual Ar Ar { get; set; }
        public virtual Darab Darab { get; set; }
        public virtual Kategoria Kategoria { get; set; }
        public virtual Keszlet Keszlet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parameter> Parameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prj_Alkatresz> Prj_Alkatresz { get; set; }
    }
}
