//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronikaiAlkatreszKeszletNyilvantarto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keszlet
    {
        public int KESZLET_ID { get; set; }
        public int ALKATRESZ_ID { get; set; }
        public double MENNYISEG { get; set; }
        public int EGYSEGAR { get; set; }
        public string MEGJEGYZES { get; set; }
    
        public virtual Alkatresz Alkatresz { get; set; }
    }
}
