
drop table dbo.Prj_Alkatresz
drop table dbo.Projekt
drop table dbo.Keszlet
drop table dbo.Parameterek
drop table dbo.Alkatresz
drop table dbo.Parameter_Def
drop table dbo.Kategoria

CREATE TABLE [Kategoria] (
    [KATEGORIA_ID] INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
    [KATEGORIA] VARCHAR (50) NOT NULL,
    [STATUSZ] BIT NOT NULL DEFAULT ((1)),
  );
 --OK
CREATE TABLE [Parameter_Def] (
    [KATEGORIA_ID] INT NOT NULL FOREIGN KEY REFERENCES [Kategoria] ([KATEGORIA_ID]),
    [PARAMETER_SORSZAM] INT NOT NULL,
    [PARAMETER_MEGNEVEZES] NVARCHAR (300) NOT NULL,
    [PARAMETER_MERTEKEGYSEG] NVARCHAR (300) NULL,
    [PARAMETER_ERTEKTIPUS] INT NOT NULL,
    CONSTRAINT [pk_Parameter_Def] PRIMARY KEY ([KATEGORIA_ID], [PARAMETER_SORSZAM]),
   
);
--OK
CREATE TABLE [Alkatresz] (
    [ALKATRESZ_ID] INT PRIMARY KEY  IDENTITY(1,1) NOT NULL,
	[MEGNEVEZES]  VARCHAR(50) NOT NULL,
	[KATEGORIA_ID] INT NOT NULL FOREIGN KEY REFERENCES [Kategoria] ([KATEGORIA_ID])
	
    
);
--OK
CREATE TABLE [Parameterek] (
    [PARAMETER_ID] INT NOT NULL FOREIGN KEY  REFERENCES [Alkatresz] ([ALKATRESZ_ID]), 
	[KATEGORIA_ID]           INT  NOT NULL ,
	[PARAMETER_SORSZAM]      INT           NOT NULL,
    [PARAMETER_ERTEK]        VARCHAR (200) NOT NULL,
    [PARAMETER_MERTEKEGYSEG] VARCHAR (20)  NULL,
    CONSTRAINT [fk_ParameterErtek-Parameter] 
		FOREIGN KEY ([KATEGORIA_ID],[PARAMETER_SORSZAM]) 
		REFERENCES [Parameter_Def] ([KATEGORIA_ID],[PARAMETER_SORSZAM]),
    
	CONSTRAINT [pk_Kategoria] 
		PRIMARY KEY ([KATEGORIA_ID],[PARAMETER_ID],[PARAMETER_SORSZAM]), 
);

CREATE TABLE [Keszlet] (
    [KESZLET_ID]   INT  NOT NULL PRIMARY KEY IDENTITY (1,1),
    [ALKATRESZ_ID] INT           NOT NULL FOREIGN KEY REFERENCES [Alkatresz] ([ALKATRESZ_ID]),
    [MENNYISEG]    FLOAT (53)    NOT NULL,
    [EGYSEGAR]     FLOAT(53)           NOT NULL,
    [MEGJEGYZES]   VARCHAR (500) NULL,
);
--ok
CREATE TABLE [Projekt] (
    [PROJEKT_ID] INT  NOT NULL PRIMARY KEY IDENTITY(1,1) ,    
    [MEGNEVEZES] VARCHAR (100)  NOT NULL,
    [LEIRAS] VARCHAR (2000) NULL,
    [MEGJEGYZES] VARCHAR (2000) NULL,
    [STATUSZ] BIT NOT NULL DEFAULT (1)
);
--ok
CREATE TABLE [Prj_Alkatresz] (
    [PROJEKT_ID]  INT NOT NULL REFERENCES [Projekt] ([PROJEKT_ID]) ,
    [ALKATRESZ_ID]  INT NOT NULL,
    [DARABSZAM] INT NOT NULL,
    [DARAB_AR] FLOAT NULL,
    CONSTRAINT [fk_Prj_Alkatresz] FOREIGN KEY ([ALKATRESZ_ID]) REFERENCES [Alkatresz] ([ALKATRESZ_ID]),
);



                     
