//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronikaiAlkatreszKeszletNyilvantarto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeszletABEntities1 : DbContext
    {
        public KeszletABEntities1()
            : base("name=KeszletABEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alkatresz> Alkatresz { get; set; }
        public virtual DbSet<Ar> Ar { get; set; }
        public virtual DbSet<Darab> Darab { get; set; }
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        public virtual DbSet<Keszlet> Keszlet { get; set; }
        public virtual DbSet<Parameter> Parameter { get; set; }
        public virtual DbSet<Prj_Alkatresz> Prj_Alkatresz { get; set; }
        public virtual DbSet<Projekt> Projekt { get; set; }
    }
}
