//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronikaiAlkatreszKeszletNyilvantarto
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterUI
    {
        public int ParameterID { get; set; }
        public string ParameterTipus { get; set; }
        public string ParameterErtek { get; set; }
        public string ParameterMegnevezes { get; set; }
    }
}
