//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronikaiAlkatreszKeszletNyilvantarto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public int ALKATRESZ_ID { get; set; }
        public int PARAMETER_SORSZAM { get; set; }
        public string PARAMETER_MEGNEVEZES { get; set; }
        public string PARAMETER_ERTEK { get; set; }
        public Nullable<int> PARAMETER_TIPUS { get; set; }
    
        public virtual Alkatresz Alkatresz { get; set; }
    }
}
