//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektronikaiAlkatreszKeszletNyilvantarto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prj_Alkatresz
    {
        public int PRJ_ALKATRESZ_ID { get; set; }
        public int PROJEKT_ID { get; set; }
        public int ALKATRESZ_ID { get; set; }
        public int ALKATRESZ_DARABSZAM { get; set; }
    
        public virtual Alkatresz Alkatresz { get; set; }
        public virtual Projekt Projekt { get; set; }
    }
}
