CREATE TABLE [Kategoria] (
    [KATEGORIA_ID] INT          IDENTITY (1, 1) NOT NULL,
    [KATEGORIA]    VARCHAR (50) NOT NULL,
    [STATUSZ]      BIT          DEFAULT ((1)) NOT NULL,
    CONSTRAINT [pk_Kategoria_id] PRIMARY KEY ([KATEGORIA_ID]),
);
 
CREATE TABLE [Parameter] (
    [KATEGORIA_ID]           INT            NOT NULL,
    [PARAMETER_SORSZAM]      INT            NOT NULL,
    [PARAMETER_MEGNEVEZES]   NVARCHAR (300)  NOT NULL,
    [PARAMETER_MERTEKEGYSEG] NVARCHAR (300) NULL,
    [PARAMETER_ERTEKTIPUS]   INT            NOT NULL,
    CONSTRAINT [pk_Parameter] PRIMARY KEY ([KATEGORIA_ID], [PARAMETER_SORSZAM]),
    CONSTRAINT [fk_Parameter-Kategoria] FOREIGN KEY ([KATEGORIA_ID]) REFERENCES [Kategoria] ([KATEGORIA_ID])
);

CREATE TABLE [Alkatresz] (
    [ALKATRESZ_ID] INT IDENTITY NOT NULL,
    [PARAMETER_ID] INT NOT NULL UNIQUE ,
    PRIMARY KEY ([ALKATRESZ_ID]),
);

CREATE TABLE [Parameter_Ertek] (
    [PARAMETER_ID] INT NOT NULL , 
	[KATEGORIA_ID]           INT  NOT NULL ,
	[PARAMETER_SORSZAM]      INT           NOT NULL,
    [PARAMETER_ERTEK]        VARCHAR (200) NOT NULL,
    [PARAMETER_MERTEKEGYSEG] VARCHAR (20)  NULL,
    CONSTRAINT [fk_ParameterErtek-Parameter] FOREIGN KEY ([KATEGORIA_ID],[PARAMETER_SORSZAM]) 
		REFERENCES [Parameter] ([KATEGORIA_ID],[PARAMETER_SORSZAM]),
    CONSTRAINT [fk_Alkatresz-ParameterErtek] FOREIGN KEY ([PARAMETER_ID]) 
		REFERENCES [Alkatresz] ([PARAMETER_ID]),
	CONSTRAINT [pk_Kategoria] PRIMARY KEY ([KATEGORIA_ID],[PARAMETER_ID],[PARAMETER_SORSZAM]), 
);

CREATE TABLE [Keszlet] (
    [KESZLET_ID]   INT  UNIQUE  NOT NULL,
    [ALKATRESZ_ID] INT           NOT NULL,
    [MENNYISEG]    FLOAT (53)    NOT NULL,
    [EGYSEGAR]     FLOAT(53)           NOT NULL,
    [MEGJEGYZES]   VARCHAR (500) NULL,
    CONSTRAINT [fk_Keszlet-Alkatresz] FOREIGN KEY ([ALKATRESZ_ID]) REFERENCES [Alkatresz] ([ALKATRESZ_ID])
);

CREATE TABLE [Projekt] (
    [PROJEKT_ID]         INT            NOT NULL,
    [PROJEKT_MEGNEVEZES] VARCHAR (200)  NOT NULL,
    [PROJEKT_LEIRAS]     VARCHAR (2000) NULL,
    PRIMARY KEY  ([PROJEKT_ID] )
);

CREATE TABLE [Prj_Alkatresz] (
    [PRJ_ALKATRESZ_ID]    INT NOT NULL,
    [PROJEKT_ID]          INT NOT NULL,
    [ALKATRESZ_ID]        INT NOT NULL,
    [ALKATRESZ_DARABSZAM] INT NOT NULL,
    PRIMARY KEY ([PRJ_ALKATRESZ_ID]),
    CONSTRAINT [fk_Prj_Alkatresz] FOREIGN KEY ([ALKATRESZ_ID]) REFERENCES [Alkatresz] ([ALKATRESZ_ID]),
    CONSTRAINT [fk_Prj_Alkatresz-Projekt] FOREIGN KEY ([PROJEKT_ID]) REFERENCES [Projekt] ([PROJEKT_ID])
);



