/*SELECT
K.KESZLET_ID,
K.ALKATRESZ_ID,
K.MENNYISEG,
K.EGYSEGAR,
K.MEGJEGYZES,
A.ALKATRESZ_ID,
A.MEGNEVEZES,
P.PARAMETER_SORSZAM,
P.PARAMETER_ERTEK,
P.PARAMETER_MERTEKEGYSEG

FROM Keszlet as K LEFT JOIN [Alkatresz] as A ON K.[ALKATRESZ_ID]=A.[ALKATRESZ_ID] left join Parameterek as P on P.PARAMETER_ID=A.ALKATRESZ_ID WHERE A.[KATEGORIA_ID]=1 and p.KATEGORIA_ID=1*/
--select * from Keszlet as K inner join alkatresz as A on k.ALKATRESZ_ID=a.ALKATRESZ_ID where a.KATEGORIA_ID=3
/*
select  
p.KATEGORIA_ID,p.PARAMETER_ID,p.PARAMETER_SORSZAM,p.PARAMETER_ERTEK,p.PARAMETER_MERTEKEGYSEG,a.MEGNEVEZES 
from Alkatresz as A inner join Parameterek as P on A.ALKATRESZ_ID=P.PARAMETER_ID 
where p.KATEGORIA_ID=a.KATEGORIA_ID and p.KATEGORIA_ID=1 */
SELECT K.[KESZLET_ID],K.[ALKATRESZ_ID],K.[MENNYISEG],K.[EGYSEGAR],K.[MEGJEGYZES] FROM [Keszlet] AS K INNER JOIN [Alkatresz] AS A ON K.[ALKATRESZ_ID]=A.[ALKATRESZ_ID] WHERE A.[KATEGORIA_ID]=2